---
- name: Deploy Kubernetes manifests
  hosts: localhost
  tasks:
    - name: Apply deployment manifest
      k8s:
        state: present
        definition: "{{ lookup('file', 'deployment.yaml') }}"
      register: deployment_result
      ignore_errors: yes

    - name: Log deployment result
      debug:
        msg: "Deployment manifest applied successfully"
      when: deployment_result is success

    - name: Log deployment failure
      debug:
        msg: "Failed to apply deployment manifest"
      when: deployment_result is failed

    - name: Apply service manifest
      k8s:
        state: present
        definition: "{{ lookup('file', 'service.yaml') }}"
      register: service_result
      ignore_errors: yes

    - name: Log service result
      debug:
        msg: "Service manifest applied successfully"
      when: service_result is success

    - name: Log service failure
      debug:
        msg: "Failed to apply service manifest"
      when: service_result is failed
